import { describe, expect, it } from 'vitest'
import { createHexDoc, insertByte, isModified, markSaved, overwriteByte, redo, removeBytes, replaceBytes, undo } from './hexEdit.ts'

const doc = (...bytes: number[]) => createHexDoc(Uint8Array.from(bytes))
const bytes = (d: ReturnType<typeof doc>) => [...d.bytes]
const marks = (d: ReturnType<typeof doc>) => [...d.changed]

describe('HexDoc', () => {
  it('overwrites a byte, marks it as changed, and is modified', () => {
    const d = doc(1, 2, 3)
    expect(isModified(d)).toBe(false)
    overwriteByte(d, 1, 0xff)
    expect(bytes(d)).toEqual([1, 255, 3])
    expect(marks(d)).toEqual([0, 1, 0])
    expect(isModified(d)).toBe(true)
  })
  it('inserts a byte (the file is longer, the bytes after it move, the new one is marked) and at the end', () => {
    const d = doc(1, 2, 3)
    overwriteByte(d, 2, 9)
    insertByte(d, 1, 7)
    expect(bytes(d)).toEqual([1, 7, 2, 9])
    expect(marks(d)).toEqual([0, 1, 0, 1])
    insertByte(d, 4, 5)
    expect(bytes(d)).toEqual([1, 7, 2, 9, 5])
  })
  it('removes a range, both ends included, also past the end (cut to it)', () => {
    const d = doc(1, 2, 3, 4, 5)
    removeBytes(d, 1, 2)
    expect(bytes(d)).toEqual([1, 4, 5])
    removeBytes(d, 1, 99)
    expect(bytes(d)).toEqual([1])
  })
  it('undoes and redoes each kind of edit, with the marks and the place', () => {
    const d = doc(1, 2, 3)
    overwriteByte(d, 0, 9)
    insertByte(d, 2, 8)
    removeBytes(d, 0, 0)
    expect(bytes(d)).toEqual([2, 8, 3])
    expect(undo(d)).toBe(0)
    expect(bytes(d)).toEqual([9, 2, 8, 3])
    expect(marks(d)).toEqual([1, 0, 1, 0])
    expect(undo(d)).toBe(2)
    expect(undo(d)).toBe(0)
    expect(bytes(d)).toEqual([1, 2, 3])
    expect(marks(d)).toEqual([0, 0, 0])
    expect(isModified(d)).toBe(false)
    expect(undo(d)).toBeNull()
    expect(redo(d)).toBe(0)
    expect(redo(d)).toBe(2)
    expect(redo(d)).toBe(0)
    expect(bytes(d)).toEqual([2, 8, 3])
    expect(redo(d)).toBeNull()
  })
  it('a new edit after an undo forgets what could be redone', () => {
    const d = doc(1, 2)
    overwriteByte(d, 0, 5)
    undo(d)
    overwriteByte(d, 1, 6)
    expect(redo(d)).toBeNull()
    expect(bytes(d)).toEqual([1, 6])
  })
  it('puts the two digits of a byte in one edit, one undo takes both back', () => {
    const d = doc(0x11, 0x22)
    overwriteByte(d, 0, 0xa1)
    overwriteByte(d, 0, 0xab, true)
    expect(bytes(d)).toEqual([0xab, 0x22])
    expect(d.undo).toHaveLength(1)
    undo(d)
    expect(bytes(d)).toEqual([0x11, 0x22])
    const i = doc(1, 2)
    insertByte(i, 1, 0xa0)
    insertByte(i, 1, 0xab, true)
    expect(bytes(i)).toEqual([1, 0xab, 2])
    expect(i.undo).toHaveLength(1)
    undo(i)
    expect(bytes(i)).toEqual([1, 2])
  })
  it('is not modified again when the edits are undone to the saved point, and the saved point survives redo', () => {
    const d = doc(1, 2, 3)
    overwriteByte(d, 0, 9)
    markSaved(d)
    expect(isModified(d)).toBe(false)
    expect(marks(d)).toEqual([0, 0, 0])
    overwriteByte(d, 1, 8)
    expect(isModified(d)).toBe(true)
    undo(d)
    expect(isModified(d)).toBe(false)
    undo(d)
    expect(isModified(d)).toBe(true)
    redo(d)
    expect(isModified(d)).toBe(false)
  })
  it('does not coalesce across a save, and loses the saved point when a new edit is made after undoing past it', () => {
    const d = doc(1, 2)
    overwriteByte(d, 0, 0xa0)
    markSaved(d)
    overwriteByte(d, 0, 0xab, true)
    expect(d.undo).toHaveLength(2)
    expect(isModified(d)).toBe(true)
    const e = doc(1, 2, 3)
    overwriteByte(e, 0, 9)
    overwriteByte(e, 1, 9)
    markSaved(e)
    undo(e)
    undo(e)
    overwriteByte(e, 2, 7)
    expect(isModified(e)).toBe(true)
    undo(e)
    expect(isModified(e)).toBe(true)
  })
  it('ignores an edit outside the file', () => {
    const d = doc(1, 2)
    overwriteByte(d, 5, 1)
    replaceBytes(d, 1, 3, Uint8Array.of(0))
    expect(bytes(d)).toEqual([1, 2])
    expect(isModified(d)).toBe(false)
  })
})
