// @vitest-environment happy-dom
import type { DirEntry, ListResult, OpResult } from '@core/api.ts'
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { I18nProvider } from '@/i18n/context.tsx'
import type { SortKey } from '@core/fs/sort.ts'
import { ENTRY_DRAG, ExplorerTree } from './ExplorerTree.tsx'

afterEach(cleanup)

const entry = (name: string, kind: DirEntry['kind'], dir = '', extra: Partial<DirEntry> = {}): DirEntry => ({ name, path: dir ? `${dir}/${name}` : name, kind, size: kind === 'dir' ? 0 : 10, modified: '2026-01-01T00:00:00.000Z', hidden: name.startsWith('.'), ...extra })
const disk: Record<string, ListResult> = {
  '': { entries: [entry('.git', 'dir'), entry('docs', 'dir'), entry('.env', 'file'), entry('a.txt', 'file'), entry('pack.zip', 'zip'), entry('page.wsnp', 'wsnp')], truncated: false },
  docs: { entries: [entry('readme.md', 'file', 'docs')], truncated: false },
  '.git': { entries: [], truncated: false },
  'pack.zip': { entries: [entry('src', 'dir', 'pack.zip!', { path: 'pack.zip!/src' })], truncated: false },
  'pack.zip!/src': { entries: [entry('main.c', 'file', 'pack.zip!/src', { path: 'pack.zip!/src/main.c' })], truncated: false },
  locked: { error: 'denied' },
}

function show({ showHidden = false, activePath, refreshToken = 0, lists = disk, kind = 'folder', trash = false, writable = false, sortKey = 'name', sortDescending = false, createRequest }: { writable?: boolean; createRequest?: { kind: 'file' | 'dir'; token: number }; showHidden?: boolean; activePath?: string; refreshToken?: number; lists?: Record<string, ListResult>; kind?: 'folder' | 'zip'; trash?: boolean; sortKey?: SortKey; sortDescending?: boolean } = {}) {
  const listDir = vi.fn(async (path: string) => lists[path] ?? ({ error: 'no-dir' } as ListResult))
  const actions = { listDir, open: vi.fn(), openSnapshot: vi.fn(), openDefault: vi.fn(), properties: vi.fn(), pin: vi.fn(), restore: vi.fn(), openWith: vi.fn(), save: vi.fn(), copy: vi.fn(), reveal: vi.fn(), create: vi.fn(async (): Promise<OpResult> => ({ ok: true, path: 'x' })), rename: vi.fn(async (): Promise<OpResult> => ({ ok: true, path: 'x' })), move: vi.fn(), moveTo: vi.fn(), remove: vi.fn() }
  type Props = { showHidden: boolean; activePath?: string; refreshToken: number; sortKey: SortKey; sortDescending: boolean }
  const tree = (props: Props) => (
    <I18nProvider language="en">
      <ExplorerTree rootId="r1" rootKind={kind} trash={trash} writable={writable} createRequest={createRequest} actions={actions} {...props} />
    </I18nProvider>
  )
  const view = render(tree({ showHidden, activePath, refreshToken, sortKey, sortDescending }))
  return { ...actions, view, again: (props: Partial<Props> & Pick<Props, 'showHidden' | 'refreshToken'>) => view.rerender(tree({ sortKey, sortDescending, ...props })) }
}
/** The names of the rows (each row also has its size and date). */
const names = () => screen.queryAllByRole('treeitem').map((r) => r.querySelector('span.truncate')?.textContent ?? r.textContent)

describe('ExplorerTree', () => {
  it('reads the root alone, and lists folders first without the hidden ones', async () => {
    const { listDir } = show()
    await waitFor(() => expect(names()).toEqual(['docs', 'a.txt', 'pack.zip', 'page.wsnp']))
    expect(listDir).toHaveBeenCalledTimes(1)
    expect(listDir).toHaveBeenCalledWith('')
    expect(screen.getByRole('tree').getAttribute('aria-label')).toBe('Files and folders')
  })
  it('does not read anything again, nor take the rows away, when it is drawn again with new functions (as the side bar does at every change)', async () => {
    const { listDir, view } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    const row = screen.getByRole('treeitem', { name: 'a.txt' })
    const again = (listDir2: typeof listDir) =>
      view.rerender(
        <I18nProvider language="en">
          <ExplorerTree rootId="r1" rootKind="folder" trash={false} writable={false} showHidden={false} sortKey="name" sortDescending={false} refreshToken={0} actions={{ listDir: listDir2, open: vi.fn(), openSnapshot: vi.fn(), openWith: vi.fn(), openDefault: vi.fn(), properties: vi.fn(), save: vi.fn(), pin: vi.fn(), restore: vi.fn(), copy: vi.fn(), reveal: vi.fn(), create: vi.fn(), rename: vi.fn(), move: vi.fn(), moveTo: vi.fn(), remove: vi.fn() }} />
        </I18nProvider>,
      )
    const other = vi.fn(async () => ({ entries: [], truncated: false }) as ListResult)
    again(other as unknown as typeof listDir)
    again(other as unknown as typeof listDir)
    expect(names()).toHaveLength(4)
    // The very same row: a double click that straddles a redraw still lands on it.
    expect(screen.getByRole('treeitem', { name: 'a.txt' })).toBe(row)
    expect(listDir).toHaveBeenCalledTimes(1)
    expect(other).not.toHaveBeenCalled()
  })
  it('shows the hidden ones, dimmed, when the switch is on, without asking the main process again', async () => {
    const { listDir, again } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    again({ showHidden: true, refreshToken: 0 })
    expect(names()).toEqual(['.git', 'docs', '.env', 'a.txt', 'pack.zip', 'page.wsnp'])
    expect(screen.getByRole('treeitem', { name: '.env' }).className).toContain('opacity-60')
    expect(listDir).toHaveBeenCalledTimes(1)
  })
  it('reads a folder when it is opened, and not before', async () => {
    const { listDir } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(screen.getByRole('treeitem', { name: 'docs' }))
    await waitFor(() => expect(names()).toEqual(['docs', 'readme.md', 'a.txt', 'pack.zip', 'page.wsnp']))
    expect(listDir).toHaveBeenCalledWith('docs')
    expect(screen.getByRole('treeitem', { name: 'docs' }).getAttribute('aria-expanded')).toBe('true')
    fireEvent.click(screen.getByRole('treeitem', { name: 'docs' }))
    expect(names()).toEqual(['docs', 'a.txt', 'pack.zip', 'page.wsnp'])
  })
  it('opens a ZIP like a folder, and the folders in it', async () => {
    show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(screen.getByRole('treeitem', { name: 'pack.zip' }))
    await waitFor(() => expect(names()).toContain('src'))
    fireEvent.click(screen.getByRole('treeitem', { name: 'src' }))
    await waitFor(() => expect(names()).toContain('main.c'))
  })
  it('opens a file in a preview tab with a click and keeps it with a double click, handing over its size', async () => {
    const { open } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(screen.getByRole('treeitem', { name: 'a.txt' }))
    expect(open).toHaveBeenLastCalledWith(expect.objectContaining({ path: 'a.txt', size: 10 }), false)
    fireEvent.doubleClick(screen.getByRole('treeitem', { name: 'a.txt' }))
    expect(open).toHaveBeenLastCalledWith(expect.objectContaining({ path: 'a.txt' }), true)
  })
  it('opens the folders above the active file, and reads them', async () => {
    const { listDir } = show({ activePath: 'pack.zip!/src/main.c' })
    await waitFor(() => expect(names()).toContain('main.c'))
    expect(listDir).toHaveBeenCalledWith('pack.zip')
    expect(listDir).toHaveBeenCalledWith('pack.zip!/src')
    expect(screen.getByRole('treeitem', { name: 'main.c' }).getAttribute('aria-selected')).toBe('true')
  })
  it('says why a folder cannot be read, in the row below it, and says when a folder is empty or has only hidden files', async () => {
    show({ lists: { '': { entries: [entry('locked', 'dir'), entry('empty', 'dir'), entry('dots', 'dir')], truncated: false }, locked: { error: 'denied' }, empty: { entries: [], truncated: false }, dots: { entries: [entry('.x', 'file', 'dots')], truncated: false } } })
    await waitFor(() => expect(names()).toHaveLength(3))
    fireEvent.click(screen.getByRole('treeitem', { name: 'locked' }))
    await screen.findByText('This folder cannot be read: the permission is missing.')
    fireEvent.click(screen.getByRole('treeitem', { name: 'empty' }))
    await screen.findByText('This folder is empty.')
    fireEvent.click(screen.getByRole('treeitem', { name: 'dots' }))
    await screen.findByText('There are only hidden files here.')
  })
  it('says when a listing was cut', async () => {
    show({ lists: { '': { entries: [entry('a.txt', 'file')], truncated: true } } })
    await screen.findByText('Only the first 1 items are shown.')
  })
  it('reads everything open again when the token changes', async () => {
    const { listDir, again } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(screen.getByRole('treeitem', { name: 'docs' }))
    await waitFor(() => expect(names()).toContain('readme.md'))
    listDir.mockClear()
    again({ showHidden: false, refreshToken: 1 })
    await waitFor(() => expect(listDir).toHaveBeenCalledWith('docs'))
    expect(listDir).toHaveBeenCalledWith('')
  })
  it('moves with the arrows, opens with the right arrow and types to a name', async () => {
    show()
    await waitFor(() => expect(names()).toHaveLength(4))
    const tree = screen.getByRole('tree')
    fireEvent.keyDown(tree, { key: 'ArrowRight' })
    await waitFor(() => expect(names()).toContain('readme.md'))
    fireEvent.keyDown(tree, { key: 'p' })
    expect(document.activeElement?.getAttribute('data-path')).toBe('pack.zip')
  })
  it('lists the rows of the context menu by kind: a ZIP can be opened as a list', async () => {
    const { open } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'pack.zip' }))
    expect(screen.getByRole('menuitem', { name: 'Open as List' })).toBeTruthy()
    fireEvent.click(screen.getByRole('menuitem', { name: 'Open as List' }))
    expect(open).toHaveBeenCalledWith(expect.objectContaining({ path: 'pack.zip', kind: 'zip' }), true)
  })
  it('previews a .wsnp with a click, as a picture would be (not opened as a snapshot), and opens it for good with a double click or Enter', async () => {
    const { openSnapshot, open } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(screen.getByRole('treeitem', { name: 'page.wsnp' }))
    expect(openSnapshot).toHaveBeenLastCalledWith(expect.objectContaining({ path: 'page.wsnp', kind: 'wsnp' }), false)
    expect(open).not.toHaveBeenCalled()
    fireEvent.doubleClick(screen.getByRole('treeitem', { name: 'page.wsnp' }))
    expect(openSnapshot).toHaveBeenLastCalledWith(expect.objectContaining({ path: 'page.wsnp' }), true)
    openSnapshot.mockClear()
    fireEvent.keyDown(screen.getByRole('tree'), { key: 'End' })
    fireEvent.keyDown(screen.getByRole('tree'), { key: 'Enter' })
    expect(openSnapshot).toHaveBeenCalledTimes(1)
  })
  it('shows a .wsnp as any file (no icon of its own), offers Open and Open as ZIP, and does not expand it', async () => {
    const { openSnapshot, open } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    expect(screen.getByRole('treeitem', { name: 'page.wsnp' }).getAttribute('aria-expanded')).toBeNull()
    expect(screen.getByRole('treeitem', { name: 'page.wsnp' }).querySelector('.codicon-browser')).toBeNull()
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'page.wsnp' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Open as ZIP' }))
    expect(open).toHaveBeenCalledWith(expect.objectContaining({ path: 'page.wsnp' }), true)
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'page.wsnp' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Open' }))
    expect(openSnapshot).toHaveBeenCalledTimes(1)
  })
  it('has, for every file, Open With…, the default application, Save As, Show in Folder, Copy Path, Copy Name and Properties, and hands each its path', async () => {
    const { openWith, openDefault, save, reveal, copy, properties } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    const choose = (name: string) => {
      fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'a.txt' }))
      fireEvent.click(screen.getByRole('menuitem', { name }))
    }
    choose('Open With…')
    expect(openWith).toHaveBeenCalledWith('a.txt')
    choose('Open with Default Application')
    expect(openDefault).toHaveBeenCalledWith('a.txt')
    choose('Save As…')
    expect(save).toHaveBeenCalledWith('a.txt')
    choose('Reveal in File Manager')
    expect(reveal).toHaveBeenCalledWith('a.txt')
    choose('Copy Path')
    expect(copy).toHaveBeenLastCalledWith('a.txt')
    choose('Copy Name')
    expect(copy).toHaveBeenLastCalledWith('a.txt')
    choose('Properties')
    expect(properties).toHaveBeenCalledWith(expect.objectContaining({ name: 'a.txt', size: 10 }))
  })
  it('has no Open With… on a folder, which expands, refreshes and has properties', async () => {
    show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'docs' }))
    expect(screen.getAllByRole('menuitem').map((m) => m.textContent?.replace(/\s+/g, ' ').trim())).toEqual(['Expand', 'Refresh', 'Add to Favorites', 'Reveal in File Manager', 'Copy Path', 'Copy Name', 'Properties'])
  })
  it('pins a folder from its menu, and a folder of a ZIP, or of a ZIP root, cannot be pinned', async () => {
    const { pin } = show()
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'docs' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Add to Favorites' }))
    expect(pin).toHaveBeenCalledWith('docs')
    fireEvent.click(screen.getByRole('treeitem', { name: 'pack.zip' }))
    await waitFor(() => expect(names()).toContain('src'))
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'src' }))
    expect(screen.queryByRole('menuitem', { name: 'Add to Favorites' })).toBeNull()
    cleanup()
    show({ kind: 'zip', lists: { '': { entries: [entry('inner', 'dir')], truncated: false } } })
    await screen.findByRole('treeitem', { name: 'inner' })
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'inner' }))
    expect(screen.queryByRole('menuitem', { name: 'Add to Favorites' })).toBeNull()
  })
  it('makes only the folders of the disk draggable to the favourites, with the root and the path', async () => {
    show()
    await waitFor(() => expect(names()).toHaveLength(4))
    expect(screen.getByRole('treeitem', { name: 'docs' }).getAttribute('draggable')).toBe('true')
    expect(screen.getByRole('treeitem', { name: 'a.txt' }).getAttribute('draggable')).toBe('false')
    const set = vi.fn()
    fireEvent.dragStart(screen.getByRole('treeitem', { name: 'docs' }), { dataTransfer: { setData: set } })
    expect(set).toHaveBeenCalledWith('application/x-folder-browser-folder', JSON.stringify({ rootId: 'r1', path: 'docs' }))
  })
  it('offers Restore on the top-level rows of the trash and nowhere else', async () => {
    const { restore } = show({ trash: true, lists: { '': { entries: [entry('old.txt', 'file'), entry('folder', 'dir')], truncated: false }, folder: { entries: [entry('in.txt', 'file', 'folder')], truncated: false } } })
    await screen.findByRole('treeitem', { name: 'old.txt' })
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'old.txt' }))
    fireEvent.click(screen.getByRole('menuitem', { name: 'Restore' }))
    expect(restore).toHaveBeenCalledWith('old.txt')
    fireEvent.click(screen.getByRole('treeitem', { name: 'folder' }))
    await screen.findByRole('treeitem', { name: 'in.txt' })
    fireEvent.contextMenu(screen.getByRole('treeitem', { name: 'in.txt' }))
    expect(screen.queryByRole('menuitem', { name: 'Restore' })).toBeNull()
  })
  describe('the order and the details of the rows', () => {
    const sized = (name: string, size: number, modified: string, kind: DirEntry['kind'] = 'file'): DirEntry => ({ name, path: name, kind, size, modified, hidden: false })
    const lists = (): Record<string, ListResult> => ({
      '': { entries: [sized('big.bin', 5_000_000, '2026-01-10T10:00:00.000Z'), sized('small.txt', 12, '2026-06-01T10:00:00.000Z'), sized('mid.md', 2048, '2025-03-05T10:00:00.000Z'), sized('zdir', 0, '2026-02-01T10:00:00.000Z', 'dir'), sized('adir', 0, '2026-09-01T10:00:00.000Z', 'dir')], truncated: false },
    })

    it('orders by name, folders first, by default', async () => {
      show({ lists: lists() })
      await waitFor(() => expect(names()).toEqual(['adir', 'zdir', 'big.bin', 'mid.md', 'small.txt']))
    })
    it('orders by size, smallest first, and largest first when descending; folders stay first and by name', async () => {
      const { again } = show({ lists: lists(), sortKey: 'size' })
      await waitFor(() => expect(names()).toEqual(['adir', 'zdir', 'small.txt', 'mid.md', 'big.bin']))
      again({ showHidden: false, refreshToken: 0, sortKey: 'size', sortDescending: true })
      expect(names()).toEqual(['adir', 'zdir', 'big.bin', 'mid.md', 'small.txt'])
    })
    it('orders by date, the oldest first, and the newest first when descending', async () => {
      const { again } = show({ lists: lists(), sortKey: 'modified' })
      await waitFor(() => expect(names()).toEqual(['zdir', 'adir', 'mid.md', 'big.bin', 'small.txt']))
      again({ showHidden: false, refreshToken: 0, sortKey: 'modified', sortDescending: true })
      expect(names()).toEqual(['adir', 'zdir', 'small.txt', 'big.bin', 'mid.md'])
    })
    it('changes the order at once, with no new reading of the folder', async () => {
      const { listDir, again } = show({ lists: lists() })
      await waitFor(() => expect(names()).toHaveLength(5))
      again({ showHidden: false, refreshToken: 0, sortKey: 'size', sortDescending: false })
      expect(names()[2]).toBe('small.txt')
      expect(listDir).toHaveBeenCalledTimes(1)
    })
    it('writes the size of a file small and to the right, and no size for a folder; the date too', async () => {
      show({ lists: lists() })
      await waitFor(() => expect(names()).toHaveLength(5))
      const row = (name: string) => screen.getByRole('treeitem', { name })
      expect(row('big.bin').textContent).toContain('4.8 MB')
      expect(row('small.txt').textContent).toContain('12 B')
      expect(row('mid.md').textContent).toContain('2.0 KB')
      // A folder has a date and no size.
      expect([...row('adir').querySelectorAll('span.tabular-nums')].map((e) => e.textContent)).toEqual([expect.stringMatching(/Sep/)])
      expect(row('adir').textContent).not.toMatch(/\d (B|KB|MB)/)
      expect(row('mid.md').textContent).toMatch(/2025/)
    })
    it('shows, when there is little room, the size when the order is by name or size, and the date when it is by date', async () => {
      const { again } = show({ lists: lists() })
      await waitFor(() => expect(names()).toHaveLength(5))
      const spans = (name: string) => [...screen.getByRole('treeitem', { name }).querySelectorAll('span.tabular-nums')].map((s) => [s.textContent, s.className.includes('hidden')])
      expect(spans('small.txt').map(([, hidden]) => hidden)).toEqual([false, true])
      again({ showHidden: false, refreshToken: 0, sortKey: 'modified', sortDescending: false })
      expect(spans('small.txt').map(([, hidden]) => hidden)).toEqual([true, false])
    })
    it('has the whole of it in the tooltip: the path, the size and the date', async () => {
      show({ lists: lists() })
      await waitFor(() => expect(names()).toHaveLength(5))
      const title = screen.getByRole('treeitem', { name: 'mid.md' }).getAttribute('title')!
      expect(title.split('\n')).toEqual(['mid.md', '2.0 KB', expect.stringContaining('2025')])
      expect(screen.getByRole('treeitem', { name: 'adir' }).getAttribute('title')!.split('\n')).toHaveLength(2)
    })
  })
})

describe('ExplorerTree: changing the disk', () => {
  const row = (name: string) => screen.getByRole('treeitem', { name })
  const nameField = () => screen.getByRole('textbox', { name: 'Name' }) as HTMLInputElement
  const rightClick = (name: string) => fireEvent.contextMenu(row(name))
  const menuItem = (name: string) => screen.getByRole('menuitem', { name })

  it('renames in the row: F2 puts a field there with the name (without its extension) selected, Enter says it', async () => {
    const { rename } = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.focus(row('a.txt'))
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    expect(nameField().value).toBe('a.txt')
    expect([nameField().selectionStart, nameField().selectionEnd]).toEqual([0, 1])
    fireEvent.change(nameField(), { target: { value: 'b.txt' } })
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    await waitFor(() => expect(rename).toHaveBeenCalledWith('a.txt', 'b.txt'))
    await waitFor(() => expect(screen.queryByRole('textbox')).toBeNull())
  })
  it('does nothing when the name did not change, and gives the field up on Escape or when the focus leaves', async () => {
    const { rename } = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    expect(rename).not.toHaveBeenCalled()
    expect(screen.queryByRole('textbox')).toBeNull()
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    fireEvent.keyDown(nameField(), { key: 'Escape' })
    expect(screen.queryByRole('textbox')).toBeNull()
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    fireEvent.blur(nameField())
    expect(screen.queryByRole('textbox')).toBeNull()
    expect(rename).not.toHaveBeenCalled()
  })
  it('refuses a bad name in words, before asking, and keeps the field; a taken name is said too', async () => {
    const { rename } = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.focus(row('a.txt'))
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    fireEvent.change(nameField(), { target: { value: 'a/b' } })
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    expect(screen.getByRole('alert').textContent).toBe('A name cannot contain / or \\.')
    expect(rename).not.toHaveBeenCalled()
    rename.mockResolvedValueOnce({ ok: false, error: 'exists' })
    fireEvent.change(nameField(), { target: { value: 'docs' } })
    expect(screen.queryByRole('alert')).toBeNull()
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    await waitFor(() => expect(screen.getByRole('alert').textContent).toBe('A file or folder with this name already exists here.'))
    expect(nameField()).toBeTruthy()
  })
  it('makes a new file or folder in a field at the top of the folder that has the focus (it opens), and in the root when none has', async () => {
    const { create, view } = show({ writable: true, createRequest: { kind: 'file', token: 1 } })
    await waitFor(() => expect(nameField().value).toBe(''))
    fireEvent.change(nameField(), { target: { value: 'new.txt' } })
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    await waitFor(() => expect(create).toHaveBeenCalledWith('', 'new.txt', 'file'))
    view.unmount()
    cleanup()
    const second = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.focus(row('docs'))
    rightClick('docs')
    fireEvent.click(menuItem('New Folder…'))
    await waitFor(() => expect(nameField()).toBeTruthy())
    expect(second.listDir).toHaveBeenCalledWith('docs')
    fireEvent.change(nameField(), { target: { value: 'sub' } })
    fireEvent.keyDown(nameField(), { key: 'Enter' })
    await waitFor(() => expect(second.create).toHaveBeenCalledWith('docs', 'sub', 'dir'))
  })
  it('asks to delete with Delete and from the menu, and to move from the menu', async () => {
    const { remove, moveTo } = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.focus(row('a.txt'))
    fireEvent.keyDown(row('a.txt'), { key: 'Delete' })
    expect(remove).toHaveBeenCalledWith(expect.objectContaining({ path: 'a.txt' }))
    rightClick('a.txt')
    fireEvent.click(menuItem('Move to…'))
    expect(moveTo).toHaveBeenCalledWith(expect.objectContaining({ path: 'a.txt' }))
    rightClick('docs')
    fireEvent.click(screen.getByRole('menuitem', { name: /^Delete/ }))
    expect(remove).toHaveBeenCalledWith(expect.objectContaining({ path: 'docs' }))
  })
  it('offers none of it where nothing can be changed: a ZIP as the root, the trash, an entry of a ZIP', async () => {
    const { remove, rename } = show({ writable: false })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.focus(row('a.txt'))
    fireEvent.keyDown(row('a.txt'), { key: 'F2' })
    fireEvent.keyDown(row('a.txt'), { key: 'Delete' })
    expect(screen.queryByRole('textbox')).toBeNull()
    expect(rename).not.toHaveBeenCalled()
    expect(remove).not.toHaveBeenCalled()
    rightClick('a.txt')
    expect(screen.queryByRole('menuitem', { name: /^Rename/ })).toBeNull()
    expect(row('a.txt').getAttribute('draggable')).toBe('false')
    cleanup()
    show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.click(row('pack.zip'))
    await waitFor(() => expect(screen.getByRole('treeitem', { name: 'src' })).toBeTruthy())
    fireEvent.focus(screen.getByRole('treeitem', { name: 'src' }))
    fireEvent.keyDown(screen.getByRole('treeitem', { name: 'src' }), { key: 'F2' })
    expect(screen.queryByRole('textbox')).toBeNull()
  })
  it('moves what is dropped on a folder into it, and what is dropped on the empty part into the root; never from another root', async () => {
    const { move } = show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    const data = (payload: unknown) => ({ dataTransfer: { types: [ENTRY_DRAG], getData: (type: string) => (type === ENTRY_DRAG ? JSON.stringify(payload) : ''), dropEffect: '' } })
    fireEvent.dragOver(row('docs'), data({ rootId: 'r1', path: 'a.txt' }))
    fireEvent.drop(row('docs'), data({ rootId: 'r1', path: 'a.txt' }))
    expect(move).toHaveBeenCalledWith('a.txt', 'docs')
    fireEvent.drop(screen.getByRole('tree'), data({ rootId: 'r1', path: 'docs/readme.md' }))
    expect(move).toHaveBeenCalledWith('docs/readme.md', '')
    fireEvent.drop(row('docs'), data({ rootId: 'other', path: 'a.txt' }))
    fireEvent.drop(row('docs'), data({ rootId: 'r1', path: 'docs' }))
    expect(move).toHaveBeenCalledTimes(2)
    // A file is not a folder: what is dropped on it goes to the folder it is in (here the root); and what is in that folder already stays.
    fireEvent.drop(row('a.txt'), data({ rootId: 'r1', path: 'docs/readme.md' }))
    expect(move).toHaveBeenCalledTimes(3)
    expect(move).toHaveBeenLastCalledWith('docs/readme.md', '')
    fireEvent.drop(row('a.txt'), data({ rootId: 'r1', path: 'b.txt' }))
    expect(move).toHaveBeenCalledTimes(3)
  })
  it('has New File and New Folder in the menu of the empty part of the tree, and Refresh', async () => {
    show({ writable: true })
    await waitFor(() => expect(names()).toHaveLength(4))
    fireEvent.contextMenu(screen.getByRole('tree'))
    expect(menuItem('New File…')).toBeTruthy()
    expect(menuItem('New Folder…')).toBeTruthy()
    expect(menuItem('Refresh')).toBeTruthy()
  })
})
